spring:
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none #режим DDL
    show-sql: true #печать sql-запросы
    generate-ddl: false #инициализация схемы при запуске

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2-console