server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarydb

mongock:
  runner-type: "ApplicationRunner" # default
#  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.mongock.changelog

  mongo-db:
    write-concern:
      journal: true
    read-concern: local

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate:  DEBUG