server:
  port: 8080
spring:
  banner:
    location: classpath:banner.txt
  messages:
    baseName: lang/messages
    encoding: UTF-8
    # Не дает свалиться в системную локаль если не найден файл для переданной в MessageSource
    # Если false то будут браться сообщения из дефолтного файла, если true, то из файла соответствующего системной локали
    fallbackToSystemLocale: false

test:
  rightAnswersCountToPass: 3
  locale: en-US
  fileNameByLocaleTag:
    ru-RU: questions/questions_ru.csv
    en-US: questions/questions.csv