version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/libraryDb
      - DATASOURCE_USERNAME=admin_library
      - DATASOURCE_PASSWORD=pswdlibrary

  postgres:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin_library
      - POSTGRES_PASSWORD=pswdlibrary
      - POSTGRES_DB=libraryDb